###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM = nompicomm

HYDRO   =   hydro
DENSITY =   density
SHEAR   =   shear

#POINTMASSES    =   pointmasses
PARTICLES      =   particles_dust
PARTICLES_SINK =   particles_sink

REAL_PRECISION = double
